development:
  paypal_merchant: X25TSHNPP9XXX    
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

test:
  paypal_merchant: X25TSHNPP9XXX  
  paypal_url: testpaypalurl

staging:
  paypal_merchant: X25TSHNPP9XXX  
  paypal_url: testpaypalurl
  
production:
  paypal_merchant: X25TSHNPP9XXX
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"