production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
  auto_index_callback: after_commit
  auto_remove_callback: after_commit

development:
  solr:
    hostname: <%= ENV['SOLR_HOST'] %>
    port: <%= ENV['SOLR_PORT'] %>
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: <%= ENV['SOLR_HOST'] %>
    port: <%= ENV['SOLR_PORT'] %>
    log_level: WARNING
    path: /solr/test
